### ISSUE TITLE
Month milestones broke milestone alignment

### ISSUE THREAD

**Issue by whizzzkid** [pln-planning-tools/Starmaps#137] opened 2022-11-17 20:41 UTC
e.g. https://www.starmaps.app/roadmap/github.com/ipfs/roadmap/issues/96

<img width="1453" alt="Screenshot 2022-11-17 at 1 40 35 PM" src="https://user-images.githubusercontent.com/1895906/202555217-cf1686b1-1975-4ccb-87da-a487c8ee0952.png">

I believe it happened here: https://github.com/pln-planning-tools/Starmaps/pull/128/files

**Comment by SgtPooki** [comment] 2022-11-17 20:49
dupe of #135

**Closed by SgtPooki** 2022-11-17 20:49 UTC
Labels: bug, MVP, P0, effort/hours
