### ISSUE TITLE
feat: on mobile, show a message at the top that says this app requires desktop or a large screen

### ISSUE THREAD

**Issue by tinytb** [pln-planning-tools/StarMaps#221] opened 2022-11-30 16:10 UTC
Until StarMaps supports mobile, a small message inviting users to go to their desktop or larger screen device may be helpful. Otherwise people may wonder if it's something wrong with their device (do I need to refresh?), or a temporary glitch. A short, simple message would clarify that this is a known issue and mobile is not supported.

**Comment by juliaxbow** [comment] 2022-11-30 16:36
This is being discussed in #136. Think we can close this issue

**Comment by SgtPooki** [comment] 2022-11-30 21:15
duplicate of #136

**Closed by SgtPooki** 2022-11-30 21:15 UTC
Labels: enhancement, good first issue, UI, post-MVP, status/ready, effort/hours, P3
